export const TeamData = [
  {
    id: 1,
    name: "Mustafa Furkan İlktürk",
    mail: "furkanilkturk@gmail.com",
    status: "Active",
    role: "CEO",
    avatar: "../../../../../public/personal.jpg",
  },
  {
    id: 2,
    name: "John Doe",
    mail: "john.doe@example.com",
    status: "Active",
    role: "CFO",
    avatar: "../../../../../public/avatars/avatar2.png",
  },
  {
    id: 3,
    name: "Emily Smith",
    mail: "emily.smith@example.com",
    status: "Active",
    role: "Project Manager",
    avatar: "../../../../../public/avatars/avatar3.png",
  },
  {
    id: 4,
    name: "Alex Johnson",
    mail: "alex.johnson@example.com",
    status: "Inactive",
    role: "Graphic Designer",
    avatar: "../../../../../public/avatars/avatar4.png",
  },
  {
    id: 5,
    name: "Sophia Kim",
    mail: "sophia.kim@example.com",
    status: "Active",
    role: "Team Leader",
    avatar: "../../../../../public/avatars/avatar5.png",
  },
  {
    id: 6,
    name: "Daniel Lee",
    mail: "daniel.lee@example.com",
    status: "Inactive",
    role: "Team Member",
    avatar: "../../../../../public/avatars/avatar6.png",
  },
];
